import type {
  CovertDocument,
  DocumentListItem,
  MimeType,
  Table,
  UpdateCellRequest,
} from '@covert/shared';

export interface NewDocument {
  ownerUid: string;
  title: string;
  fileType: MimeType;
  pageCount: number;
  summary: string;
  warnings: string[];
  tables: Table[];
  ocrText: string;
}

export type CellTarget = Omit<UpdateCellRequest, 'value'>;

/**
 * Every read and write is scoped to an owner. A document owned by someone else
 * behaves exactly like one that does not exist, so ids reveal nothing.
 */
export interface DocumentRepository {
  create(input: NewDocument): Promise<CovertDocument>;
  list(ownerUid: string, limit: number): Promise<DocumentListItem[]>;
  get(ownerUid: string, id: string): Promise<CovertDocument | null>;
  rename(ownerUid: string, id: string, title: string): Promise<DocumentListItem | null>;
  /** `null` when the document is missing or not owned; `'no-cell'` when the cell is unknown. */
  updateCell(
    ownerUid: string,
    id: string,
    target: CellTarget,
    value: string,
  ): Promise<{ updatedAt: string } | 'no-cell' | null>;
  delete(ownerUid: string, id: string): Promise<boolean>;
  deleteAll(ownerUid: string): Promise<number>;
}

export function isOwnedBy(record: { ownerUid?: unknown } | undefined | null, uid: string): boolean {
  return (
    typeof uid === 'string' &&
    uid.length > 0 &&
    typeof record?.ownerUid === 'string' &&
    record.ownerUid === uid
  );
}

/** Firestore ids generated by COVERT; anything else cannot exist. */
export function isValidDocumentId(id: string): boolean {
  return /^[A-Za-z0-9_-]{1,64}$/.test(id);
}

/** Firestore documents are capped at 1 MiB; stay comfortably below it. */
export const MAX_RECORD_BYTES = 900_000;

export function estimateRecordBytes(input: NewDocument): number {
  return Buffer.byteLength(JSON.stringify(input), 'utf8');
}
